askme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
]

forum/urls.py
from django.urls import path
from forum.views import *
from django.conf import settings as django_settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='about'),
    path('ask', ask, name='ask'),
    path('<int:question_id>', question, name='question'),
    path('<int:tag_id>', tag, name='tag'),
    path('settings', settings_view, name='settings'),
    path('login', login_view, name='login'),
    path('signup', signup, name='signup'),
    path('logout', logout_view, name='logout'),
    path('hot', hot, name='hot'),
    path('api/like/', like),
    path('api/dislike/', dislike),
] + static(django_settings.MEDIA_URL, document_root=django_settings.MEDIA_ROOT)

forum/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.utils import timezone
from django import forms
from django.shortcuts import get_object_or_404


class ModelManager(models.Manager):
    def top(self):
        return self.order_by('rating')[::-1]

    def tag(self, tag_id):
        tags = get_object_or_404(Tag, pk=int(tag_id))
        return self.filter(tag__id=tags.id)

    def answer(self, question_id):
        question = get_object_or_404(Question, pk=int(question_id))
        return self.filter(question__id=question.id)

    def new(self):
        return self.order_by()[::-1]


class Tag(models.Model):
    name = models.CharField(max_length=200, unique=True)


class Profile(AbstractUser):
    nickname = models.CharField(max_length=200)
    avatar_path = models.ImageField(upload_to="", default="ymlql7_SavanB2.jpg")


class Question(models.Model):
    objects = ModelManager()
    title = models.CharField(max_length=200)
    question_text = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    create_at = models.DateTimeField(default=timezone.now)
    rating = models.SmallIntegerField(default=0)

    @property
    def total_likes(self):
        return self.likes.count() - self.dislikes.count()

    @property
    def get_avatar(self):
        return self.author.avatar_path

    class Meta:
        ordering = ['-create_at']


class Answer(models.Model):
    objects = ModelManager()
    comment = models.TextField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answer')
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='author')
    create_at = models.DateTimeField(default=timezone.now)
    rating = models.SmallIntegerField(default=0)

    @property
    def get_avatar(self):
        return self.author.avatar_path

    class Meta:
        ordering = ['-create_at']


class SignupForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Profile
        fields = ('username', 'email', 'nickname', 'password', 'avatar_path',)

    def clean(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('confirm_password')
        print(password1)
        print(password2)
        if password1 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")

        return self.cleaned_data


class AskForm(forms.ModelForm):
    tag_list = forms.CharField(max_length=500, initial="", required=True)

    class Meta:
        model = Question
        fields = ('title', 'question_text')


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('comment', )


class SettingsForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('username', 'email', 'nickname', 'avatar_path',)


class Like(models.Model):
    question = models.ForeignKey(Question, related_name="likes", on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, related_name="question_likes", on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('user', 'question')


class Dislike(models.Model):
    question = models.ForeignKey(Question, related_name="dislikes", on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, related_name="question_dislikes", on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('user', 'question')

forum/views.py
from django.db import IntegrityError
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.views.generic import TemplateView
from .models import *
from django.contrib.auth.decorators import permission_required, login_required
from django.core.paginator import Paginator
from django.db.models import Count
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def paginate(objects, request, amount):
    paginator = Paginator(objects, amount)
    page = request.GET.get('page')
    objects_page = paginator.get_page(page)
    return objects_page


def render_question(request, file, objects):
    template = loader.get_template(file)
    context = {
        'questions': paginate(objects, request, 5),
    }
    return HttpResponse(template.render(context, request))


def question(request, question_id):
    if request.method == 'POST':
        form = AnswerForm(data=request.POST)
        if form.is_valid:
            answer = form.save(commit=False)
            answer.author = request.user
            answer.question = Question.objects.get(id=question_id)
            answer.save()
            return redirect('question', question_id)

    form = AnswerForm()
    answers = Answer.objects.answer(question_id)
    template = loader.get_template('question.html')
    context = {
        'form': form,
        'answers': paginate(answers, request, 5),
        'question': Question.objects.get(id=question_id)
    }
    return HttpResponse(template.render(context, request))


def tag(request, tag_id):
    latest_question_list = Question.objects.tag(tag_id)
    template = loader.get_template('tag.html')
    context = {
        'questions': paginate(latest_question_list, request, 5),
        'tag': Tag.objects.get(id=tag_id)
    }
    return HttpResponse(template.render(context, request))


@login_required(login_url='login')
def like(request):
    question = Question.objects.get(pk=request.POST['id'])
    new_like = Like(question=question, user=request.user)
    try:
        dislike = question.dislikes.filter(user=request.user)
        if dislike:
            dislike.delete()
        new_like.save()
        question.rating = question.likes.count() - question.dislikes.count()
        question.save()
    except IntegrityError as e:
        question.likes.filter(user=request.user).delete()
    return JsonResponse({'total_likes': question.total_likes})


@login_required(login_url='login')
def dislike(request):
    question = Question.objects.get(pk=request.POST['id'])
    new_dislike = Dislike(question=question, user=request.user)
    try:
        like = question.likes.filter(user=request.user)
        if like:
            like.delete()
        new_dislike.save()
        question.rating = question.likes.count() - question.dislikes.count()
        question.save()
    except IntegrityError as e:
        question.dislikes.filter(user=request.user).delete()
    return JsonResponse({'total_likes': question.total_likes})


def index(request):
    latest_question_list = Question.objects.new()
    return render_question(request, 'index.html', latest_question_list)


def hot(request):
    latest_question_list = Question.objects.all().order_by('rating')[::-1]
    return render_question(request, 'hot.html', latest_question_list)


@login_required(login_url='login')
def ask(request):
    if request.method == 'POST':
        form = AskForm(data=request.POST)
        if form.is_valid:
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            for tag in form['tag_list'].data.split():
                new_tag = Tag.objects.get_or_create(name=tag)
                print(new_tag)
                question.tag.add(new_tag[0])
            question.save()
            return redirect('question', question.id)

    if request.method == 'GET':
        form = AskForm()
    return render(request, 'ask.html', {'form': form})


@login_required(login_url='login')
def settings_view(request):
    if request.method == 'POST':
        form = SettingsForm(data=request.POST, files=request.FILES, instance=request.user)
        if form.is_valid:
            user = form.save(commit=False)
            user.save()
        return render(request, 'settings.html', {'form': form})
    if request.method == 'GET':
        form = SettingsForm(instance=request.user)
    return render(request, 'settings.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST, files=request.FILES)
        print(form.errors)
        if form.is_valid():
            user = form.get_user()
            if user is not None:
                login(request, user)
                return redirect('about')
    if request.method == 'GET':
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('login')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(data=request.POST, files=request.FILES)
        print(form.errors)
        if form.is_valid():
            print("valid")
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()
            return redirect('login')

    form = SignupForm()
    context = {
        'form': form
    }
    return render(request, 'signup.html', context)
# Create your views here.

forum/templates/answer.html
{% load static %}

<div class="row question-container question-container-border">
    <div class="col-3">
        <div class="row justify-content-center">
            <img src="media/{{ answer.get_avatar }}" class="user-gravatar32">
        </div>
    </div>
    <div class="col-9">
        <div class="row">
            <p>{{ answer.comment }}</p>
        </div>
        <div class="row mb-0">
            <div class="col-4">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Correct!
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>

forum/templates/ask.html
{% extends "base.html" %}

{% block blogmain %}
    <div class="row">
        <div class="col-4">
            <h4>New question</h4>
        </div>
    </div>

    <form method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="inputTitle" class="col-sm-2 col-form-label">Title</label>
            <input type="text" class="rounded" name="title" required id="id_title">
            <div class="invalid-feedback">
                Please enter a title
            </div>
        </div>

        <div class="form-group row">
            <label for="comment" class="col-sm-2 col-form-label">Question</label>
            <textarea class="rounded" type="text" name="question_text" required id="id_question_text" rows="10" cols="50"></textarea>
                <div class="invalid-feedback">
                    Please enter a question
                </div>
        </div>

        <div class="form-group row">
            <label for="inputTags" class="col-sm-2 col-form-label">Tags</label>
            <input type="text" class="rounded" name="tag_list" required id="id_tag_list">
                <div class="invalid-feedback">
                    Please add tags
                </div>
        </div>

        <button class="btn btn-primary my-2 my-sm-0" type="submit">Ask!</button>
    </form>
{% endblock %}

forum/templates/base.html
{% load static %}

<html>
<head>
    <title>Forum</title>
    <meta name="viewport" content="width-device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/css_bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-grid.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-reboot.css" %}">
</head>
<body>
{% include 'inc/navbar.html' %}
<style>
    * {
        font-family: "Roboto", "Lucida Grande", "DejaVu Sans", "Bitstream Vera Sans", Verdana, Arial, sans-serif;
    }
</style>
<main role="main" class="container">
    {% block container %}
        <div class="row">
        <div class="col-md-8">
            {% block blogmain %}
            {% endblock %}
        </div><!-- /.blog-main -->

        {% include 'inc/sidebar.html' %}

    {% endblock %}
    </div>
</main>
{% block scripts %}
{% endblock %}
</body>
</html>

forum/templates/hot.html
{% extends "index.html"%}

{%block tag%}
    <div class="col-4 my-lg-3">
        <h4><a href="{% url 'hot' %}" class="font-italic">Hot Questions</a></h4>
    </div>
    <div class="col-8 my-lg-3">
        <h4><a href="{% url 'about' %}">New Questions</a></h4>
    </div>
{%endblock%}

forum/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block blogmain %}
    <div class="row">
        {% block tag %}
            <div class="col-4 my-lg-3">
                <h4><a href="{% url 'about' %}" class="font-italic">New Questions</a></h4>
            </div>
            <div class="col-8 my-lg-3">
                <h4><a href="{% url 'hot' %}">Hot Questions</a></h4>
            </div>
        {% endblock %}
    </div>

    <div class="row my-lg-5">
        {% for question in questions %}
            {% include "inc/question_detail.html" %}
        {% endfor %}
    </div>

    <div class="row justify-content-center pag my-lg-5">
        <ul class="pagination">
            {%if questions.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">first</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ questions.previous_page_number}}">previous</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link">{{ questions.number }}</a></li>
            {% if questions.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ questions.next_page_number }}">next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ questions.paginator.num_pages }}">last</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/question_like.js'%}"></script>
{% endblock %}

forum/templates/login.html
{% extends "index.html"%}

{% block blogmain %}
    <div class="col-md-8 mx-auto my-lg-5">
        <form method="post" class="post-form">
            {% csrf_token %}
            <h4 class="h3 mb-3 font-weight-normal">Log in</h4>
            <div class="form-group row">
                <label for="inputTitle" class="col-sm-2 col-form-label">Login</label>
                <div class="col-sm-4">
                    {{ form.username }}
                </div>
            </div>


            <div class="form-group row">
                <label for="inputTitle" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-4">
                    {{ form.password }}
                </div>
            </div>
            <div class="form-group row">
                <label for="inputTitle" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-4">
                    <button class="btn btn-primary" type="submit">Login!</button>
                </div>
            </div>
        </form>
        <div class="form-group row">
            <label for="inputTitle" class="col-sm-2 col-form-label"></label>
            <div class="col-sm">
                <a href="{% url 'signup' %}">Create new account</a>
            </div>
        </div>
    </div>
{% endblock %}

forum/templates/question.html
{% extends "base.html" %}

{% block blogmain %}
    <div class="row question-container question-container-border my-lg-3" style="width: 100%">
        <div class="col-3">
            <div class="row justify-content-center">
                {% load static %}
                <img src="media/{{ question.get_avatar }}" class="user-gravatar32">
            </div>
            <div class="row justify-content-center like-c">
                Likes: {{ question.total_likes }}
            </div>
        </div>
        <div class="col-9">
            <div class="row">
                <h3>{{ question.title }}</h3>
            </div>
            <div class="row">
                <p>{{ question.question_text }}</p>
            </div>
            <div class="row mb-0">
                <div class="col-8">
                    Tags:
                    {% for tag in question.tag.all %}
                        <a href="{% url 'tag' tag.id %}" methods="post"> {{ tag.name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    {% for answer in answers %}
        {% include "answer.html" %}
    {% endfor %}

    {% if user.is_authenticated and user.is_active %}
        <form method="post" class="my-lg-1">
            {% csrf_token %}
            <div class="form-group">
                <div class="row mx-lg-3">
                    {#                    {{ form.comment }}#}
                    <textarea type="text" class="form-control" rows="5" cols="50" name="comment" required
                              id="id_comment"></textarea>
                </div>
            </div>
            <button class="btn btn-primary my-2 my-sm-0 mx-3" type="submit">Comment!</button>
        </form>
    {% endif %}

    <div class="row justify-content-center pag my-lg-5">
        <ul class="pagination">
            {% if answers.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ answers.previous_page_number }}">previous</a>
                </li>
            {% endif %}
            <li class="page-item"><a class="page-link">{{ answers.number }}</a></li>
            {% if answers.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ answers.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ answers.paginator.num_pages }}">last</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

forum/templates/settings.html
{% extends "index.html"%}
{% block blogmain %}
{% block tag %}
<div class="row qtype">
    <h4>Settings: {{user.username }}</h4>
    </div>
    {% endblock %}
    <form method="post" enctype="multipart/form-data" class="post-form">{% csrf_token %}
    <div class="form-group row">
            <label class="col-sm-2 col-form-label">Login:</label>
            <div class="col-sm-4">
                {{ form.username }}
            </div>
            {% if form.username.errors %}
                <div class="alert alert-danger">
                    <strong>{{ form.username.errors }}</strong>
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Email:</label>
            <div class="col-sm-4">
                {{ form.email }}
            </div>
            {% if form.email.errors %}
                <div class="alert alert-danger">
                    <strong>{{ form.email.errors }}</strong>
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Nickname:</label>
            <div class="col-sm-4">
                {{ form.nickname }}
            </div>
            {% if form.nickname.errors %}
                <div class="alert alert-danger">
                    <strong>{{ form.nickname.errors }}</strong>
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Upload Avatar:</label>
            <div class="col-6" id="Image">
                {{ form.avatar_path }}
            </div>
            {% if form.avatar_path.errors %}
                <div class="alert alert-danger">
                    <strong>{{ form.avatar_path.errors }}</strong>
                </div>
            {% endif %}
        </div>

        <button class="btn btn-primary my-2 my-sm-0" type="submit">Save!</button>
    </form>
{% endblock %}

forum/templates/signup.html
{% extends "index.html"%}
{% block blogmain %}
{% block tag %}
<div class="row qtype">
    <h4>Sign up:</h4>
    </div>
    {% endblock %}


    <form enctype="multipart/form-data" method="POST" class="post-form">
        {% csrf_token %}

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Login:</label>
            <div class="col-sm-4">
                {{ form.username }}
            </div>
            {% if form.username.errors %}
                <div class="alert alert-danger">
                    <strong>{{ form.username.errors }}</strong>
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Email:</label>
            <div class="col-sm-4">
                {{ form.email }}
            </div>
            {% if form.email.errors %}
                <div class="alert alert-danger">
                    <strong>{{ form.email.errors }}</strong>
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Nickname:</label>
            <div class="col-sm-4">
                {{ form.nickname }}
            </div>
            {% if form.nickname.errors %}
                <div class="alert alert-danger">
                    <strong>{{ form.nickname.errors }}</strong>
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Password:</label>
            <div class="col-sm-4">
                {{ form.password }}
            </div>
            {% if form.password.errors %}
                <div class="alert alert-danger">
                    <strong>{{ form.password.errors }}</strong>
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Repeat password:</label>
            <div class="col-sm-4">
               {{ form.confirm_password }}
            </div>
            {% if form.confirm_password.errors %}
                <div class="alert alert-danger">
                    <strong>{{ form.confirm_password.errors }}</strong>
                </div>
            {% endif %}
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Choose avatar:</label>
            <div class="col-sm-4">
                {{ form.avatar_path }}
            </div>
            {% if form.avatar_path.errors %}
                <div class="alert alert-danger">
                    <strong>{{ form.avatar_path.errors }}</strong>
                </div>
            {% endif %}
        </div>

        <button class="btn btn-primary my-2 my-sm-0" type="submit">Register!</button>
    </form>
 {% endblock %}

forum/templates/tag.html
{% extends "index.html"%}
{% block tag %}
    <div class="row">
        <h4>Tag: {{ tag.name }}</h4>
    </div>
{% endblock %}